### ISSUE TITLE
CLI Error: Navigating frame was detached

### ISSUE THREAD

**Issue by fellyph** [GoogleChromeLabs/ps-analysis-tool#300]
**Describe the bug**
Running the CLI Sitemap Report at indiatoday.in and got the following error

```
Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106
            this.#terminationDeferred.resolve(new Error('Navigating frame was detached'));
                                              ^

Error: Navigating frame was detached
    at LifecycleWatcher.#onFrameDetached (/Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:47)
    at /Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:1:269
    at Array.map (<anonymous>)
    at Object.emit (/Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:1:252)
    at Frame.emit (/Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:88:22)
    at FrameManager.#removeFramesRecursively (/Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:394:15)
    at /Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:90:46
    at onceHandler (/Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:99:13)
    at /Users/blog-fellyph/Local Sites/ps-analysis-tool/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:1:269
    at Array.map (<anonymous>)
```

**To Reproduce**
1. run the CLI with the URL: `npm run cli -- -s https://blog.fellyph.com.br/sitemap_index.xml`

**Expected behavior**
Finish the report if something went wrong

**Screenshots**
<img width="1078" alt="Screenshot 2023-11-27 at 07 13 31" src="https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/330792/d5e4ff53-035b-4ef2-94d2-dffa4f96a575">

**Desktop (please complete the following information):**
 - OS: macOS 14.0 (23A344)
 - Browser 119.0.6045.159 (Official Build) (arm64) 
 - Version develop

**Additional context**

**Comment by kjnanda** [comment]
I also faced this issue while checking out the code from main branch. After the error was encountered and retrying the same command was working as exepcted.

<kbd>![image](https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/f9436bb8-feb6-4664-a81d-f2966f562180)</kbd>

**Comment by fellyph** [comment]
@ayushnirwal I have tested with `main` branch with sitemaps with:

-  60 URLs
-  80 URLs
- 140 URLs

The three tests passed.
